# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Res import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.323, y1:0.278409, x2:0.825871, y2:0.108, stop:0 rgba(37, 37, 37, 255), stop:1 rgba(40, 40, 40, 255));")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Setup_Page = QtWidgets.QWidget()
        self.Setup_Page.setObjectName("Setup_Page")
        self.label = QtWidgets.QLabel(self.Setup_Page)
        self.label.setGeometry(QtCore.QRect(425, 90, 150, 150))
        self.label.setStyleSheet("border-radius:75px;\n"
"border-image: url(:/Logo/Logo/App Logo.png);")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Name_txt = QtWidgets.QLineEdit(self.Setup_Page)
        self.Name_txt.setGeometry(QtCore.QRect(250, 290, 500, 40))
        self.Name_txt.setStyleSheet("QLineEdit\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border:0px;\n"
"    border-radius:10px;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:15px;\n"
"}\n"
"\n"
"QLineEdit:focus\n"
"{\n"
"    border:2px solid #ff004f;\n"
"    color:#ff004f;\n"
"}")
        self.Name_txt.setObjectName("Name_txt")
        self.Email_txt = QtWidgets.QLineEdit(self.Setup_Page)
        self.Email_txt.setGeometry(QtCore.QRect(250, 370, 500, 40))
        self.Email_txt.setStyleSheet("QLineEdit\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border:0px;\n"
"    border-radius:10px;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:15px;\n"
"}\n"
"\n"
"QLineEdit:focus\n"
"{\n"
"    border:2px solid #ff004f;\n"
"    color:#ff004f;\n"
"}")
        self.Email_txt.setObjectName("Email_txt")
        self.otp_txt = QtWidgets.QLineEdit(self.Setup_Page)
        self.otp_txt.setGeometry(QtCore.QRect(250, 450, 271, 40))
        self.otp_txt.setStyleSheet("QLineEdit\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border:0px;\n"
"    border-radius:10px;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:15px;\n"
"}\n"
"\n"
"QLineEdit:focus\n"
"{\n"
"    border:2px solid #ff004f;\n"
"    color:#ff004f;\n"
"}")
        self.otp_txt.setObjectName("otp_txt")
        self.otp_button = QtWidgets.QPushButton(self.Setup_Page)
        self.otp_button.setGeometry(QtCore.QRect(550, 450, 200, 40))
        self.otp_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.otp_button.setStyleSheet("QPushButton\n"
"{\n"
"    \n"
"    background-color: rgb(255, 0, 79);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    color: rgb(255, 0, 79);\n"
"}")
        self.otp_button.setObjectName("otp_button")
        self.Submit_button = QtWidgets.QPushButton(self.Setup_Page)
        self.Submit_button.setGeometry(QtCore.QRect(250, 530, 500, 40))
        self.Submit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Submit_button.setStyleSheet("QPushButton\n"
"{\n"
"    \n"
"    background-color: rgb(255, 0, 79);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    color: rgb(255, 0, 79);\n"
"}")
        self.Submit_button.setObjectName("Submit_button")
        self.Minimize_btn_2 = QtWidgets.QPushButton(self.Setup_Page)
        self.Minimize_btn_2.setGeometry(QtCore.QRect(880, 20, 50, 40))
        self.Minimize_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Minimize_btn_2.setStyleSheet("border:none;")
        self.Minimize_btn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/Minimize icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Minimize_btn_2.setIcon(icon)
        self.Minimize_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.Minimize_btn_2.setObjectName("Minimize_btn_2")
        self.Exit_btn_2 = QtWidgets.QPushButton(self.Setup_Page)
        self.Exit_btn_2.setGeometry(QtCore.QRect(930, 20, 50, 40))
        self.Exit_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Exit_btn_2.setStyleSheet("border:none;")
        self.Exit_btn_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/Exit Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_btn_2.setIcon(icon1)
        self.Exit_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.Exit_btn_2.setObjectName("Exit_btn_2")
        self.stackedWidget.addWidget(self.Setup_Page)
        self.Main_Page = QtWidgets.QWidget()
        self.Main_Page.setObjectName("Main_Page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Main_Page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Menu_Container = QtWidgets.QFrame(self.Main_Page)
        self.Menu_Container.setMinimumSize(QtCore.QSize(250, 800))
        self.Menu_Container.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Menu_Container.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.Menu_Container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu_Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Container.setObjectName("Menu_Container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Menu_Container)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.Menu_Container)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 350))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 150, 50, 40))
        self.pushButton_7.setStyleSheet("background:transparent;\n"
"\n"
"")
        self.pushButton_7.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/Home Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.Home_Menu = QtWidgets.QLabel(self.frame_5)
        self.Home_Menu.setGeometry(QtCore.QRect(70, 155, 121, 30))
        self.Home_Menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Home_Menu.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial Rounded MT Bold\";")
        self.Home_Menu.setObjectName("Home_Menu")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 200, 50, 40))
        self.pushButton_8.setStyleSheet("background:transparent;\n"
"\n"
"")
        self.pushButton_8.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/Search Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.Search_Menu = QtWidgets.QLabel(self.frame_5)
        self.Search_Menu.setGeometry(QtCore.QRect(70, 205, 121, 30))
        self.Search_Menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_Menu.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial Rounded MT Bold\";")
        self.Search_Menu.setObjectName("Search_Menu")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 250, 50, 40))
        self.pushButton_9.setStyleSheet("background:transparent;\n"
"\n"
"")
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/Favourite Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.Favourite_Menu = QtWidgets.QLabel(self.frame_5)
        self.Favourite_Menu.setGeometry(QtCore.QRect(70, 255, 121, 30))
        self.Favourite_Menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Favourite_Menu.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial Rounded MT Bold\";")
        self.Favourite_Menu.setObjectName("Favourite_Menu")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(60, 20, 100, 100))
        self.label_8.setStyleSheet("border-radius:50px;\n"
"border-image: url(:/Logo/Logo/App Logo.png);")
        self.label_8.setText("")
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.Menu_Container)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 200, 200))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255,50%);\n")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(19, 230, 200, 30))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial Rounded MT Bold\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(20, 265, 220, 20))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255,50%);\n"
"font: 10pt \"Arial Rounded MT Bold\";")
        self.label_4.setObjectName("label_4")
        self.Previous_Song_btn = QtWidgets.QPushButton(self.frame_6)
        self.Previous_Song_btn.setGeometry(QtCore.QRect(10, 300, 50, 40))
        self.Previous_Song_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Previous_Song_btn.setToolTip("")
        self.Previous_Song_btn.setStyleSheet("background:transparent;")
        self.Previous_Song_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/Backward Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Previous_Song_btn.setIcon(icon5)
        self.Previous_Song_btn.setIconSize(QtCore.QSize(30, 30))
        self.Previous_Song_btn.setObjectName("Previous_Song_btn")
        self.Next_Song_btn = QtWidgets.QPushButton(self.frame_6)
        self.Next_Song_btn.setGeometry(QtCore.QRect(150, 300, 50, 40))
        self.Next_Song_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Next_Song_btn.setToolTip("")
        self.Next_Song_btn.setStyleSheet("background:transparent;")
        self.Next_Song_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/Forward Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Next_Song_btn.setIcon(icon6)
        self.Next_Song_btn.setIconSize(QtCore.QSize(30, 30))
        self.Next_Song_btn.setObjectName("Next_Song_btn")
        self.Play_Pause_btn = QtWidgets.QPushButton(self.frame_6)
        self.Play_Pause_btn.setGeometry(QtCore.QRect(80, 300, 50, 40))
        self.Play_Pause_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Play_Pause_btn.setToolTip("")
        self.Play_Pause_btn.setStyleSheet("background:transparent;")
        self.Play_Pause_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/play Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play_Pause_btn.setIcon(icon7)
        self.Play_Pause_btn.setIconSize(QtCore.QSize(30, 30))
        self.Play_Pause_btn.setObjectName("Play_Pause_btn")
        self.line = QtWidgets.QFrame(self.frame_6)
        self.line.setGeometry(QtCore.QRect(0, 360, 251, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Favourite_btn = QtWidgets.QPushButton(self.frame_6)
        self.Favourite_btn.setGeometry(QtCore.QRect(10, 380, 50, 40))
        self.Favourite_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Favourite_btn.setStyleSheet("background:transparent;\n"
"\n"
"")
        self.Favourite_btn.setText("")
        self.Favourite_btn.setIcon(icon4)
        self.Favourite_btn.setIconSize(QtCore.QSize(25, 25))
        self.Favourite_btn.setObjectName("Favourite_btn")
        self.mp3_btn = QtWidgets.QPushButton(self.frame_6)
        self.mp3_btn.setGeometry(QtCore.QRect(80, 380, 50, 40))
        self.mp3_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mp3_btn.setStyleSheet("background:transparent;\n"
"\n"
"")
        self.mp3_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/Mp3 Download Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mp3_btn.setIcon(icon8)
        self.mp3_btn.setIconSize(QtCore.QSize(25, 25))
        self.mp3_btn.setObjectName("mp3_btn")
        self.mp4_btn = QtWidgets.QPushButton(self.frame_6)
        self.mp4_btn.setGeometry(QtCore.QRect(150, 380, 50, 40))
        self.mp4_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mp4_btn.setStyleSheet("background:transparent;\n"
"\n"
"")
        self.mp4_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icons/Mp4 Download Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mp4_btn.setIcon(icon9)
        self.mp4_btn.setIconSize(QtCore.QSize(25, 25))
        self.mp4_btn.setObjectName("mp4_btn")
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.Menu_Container)
        self.frame_2 = QtWidgets.QFrame(self.Main_Page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(741, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Search_txt = QtWidgets.QLineEdit(self.frame)
        self.Search_txt.setGeometry(QtCore.QRect(39, 10, 441, 40))
        self.Search_txt.setStyleSheet("QLineEdit\n"
"{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border:0px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    padding-left:15px;\n"
"    \n"
"    font: 9pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus\n"
"{\n"
"    \n"
"    color: rgb(255, 0, 79);\n"
"    border:2px solid #ff004f;\n"
"}")
        self.Search_txt.setObjectName("Search_txt")
        self.Search_btn = QtWidgets.QPushButton(self.frame)
        self.Search_btn.setGeometry(QtCore.QRect(480, 10, 50, 40))
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("QPushButton\n"
"{\n"
"    \n"
"    \n"
"    background-color: rgb(108, 108, 108);\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Search_btn.setText("")
        self.Search_btn.setIcon(icon3)
        self.Search_btn.setObjectName("Search_btn")
        self.Exit_btn = QtWidgets.QPushButton(self.frame)
        self.Exit_btn.setGeometry(QtCore.QRect(670, 10, 50, 40))
        self.Exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Exit_btn.setStyleSheet("border:none;")
        self.Exit_btn.setText("")
        self.Exit_btn.setIcon(icon1)
        self.Exit_btn.setIconSize(QtCore.QSize(30, 30))
        self.Exit_btn.setObjectName("Exit_btn")
        self.Minimize_btn = QtWidgets.QPushButton(self.frame)
        self.Minimize_btn.setGeometry(QtCore.QRect(620, 10, 50, 40))
        self.Minimize_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Minimize_btn.setStyleSheet("border:none;")
        self.Minimize_btn.setText("")
        self.Minimize_btn.setIcon(icon)
        self.Minimize_btn.setIconSize(QtCore.QSize(30, 30))
        self.Minimize_btn.setObjectName("Minimize_btn")
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("background:transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.F1 = QtWidgets.QFrame(self.frame_4)
        self.F1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F1.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.F1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F1.setObjectName("F1")
        self.T1 = QtWidgets.QLabel(self.F1)
        self.T1.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T1.setStyleSheet("background-color: rgb(255, 255, 255,50%);")
        self.T1.setText("")
        self.T1.setScaledContents(True)
        self.T1.setObjectName("T1")
        self.TL1 = QtWidgets.QLabel(self.F1)
        self.TL1.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL1.setText("")
        self.TL1.setWordWrap(True)
        self.TL1.setObjectName("TL1")
        self.gridLayout.addWidget(self.F1, 0, 0, 1, 1)
        self.F2 = QtWidgets.QFrame(self.frame_4)
        self.F2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F2.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.F2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F2.setObjectName("F2")
        self.T2 = QtWidgets.QLabel(self.F2)
        self.T2.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T2.setStyleSheet("background-color: rgb(255, 255, 255,50%);\n"
"")
        self.T2.setText("")
        self.T2.setScaledContents(True)
        self.T2.setObjectName("T2")
        self.TL2 = QtWidgets.QLabel(self.F2)
        self.TL2.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL2.setText("")
        self.TL2.setWordWrap(True)
        self.TL2.setObjectName("TL2")
        self.gridLayout.addWidget(self.F2, 0, 1, 1, 1)
        self.F3 = QtWidgets.QFrame(self.frame_4)
        self.F3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F3.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.F3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F3.setObjectName("F3")
        self.T3 = QtWidgets.QLabel(self.F3)
        self.T3.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T3.setStyleSheet("background-color: rgb(255, 255, 255,50%);")
        self.T3.setText("")
        self.T3.setScaledContents(True)
        self.T3.setObjectName("T3")
        self.TL3 = QtWidgets.QLabel(self.F3)
        self.TL3.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL3.setText("")
        self.TL3.setWordWrap(True)
        self.TL3.setObjectName("TL3")
        self.gridLayout.addWidget(self.F3, 0, 2, 1, 1)
        self.F4 = QtWidgets.QFrame(self.frame_4)
        self.F4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F4.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.F4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F4.setObjectName("F4")
        self.T4 = QtWidgets.QLabel(self.F4)
        self.T4.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T4.setStyleSheet("background-color: rgb(255, 255, 255,50%);")
        self.T4.setText("")
        self.T4.setScaledContents(True)
        self.T4.setObjectName("T4")
        self.TL4 = QtWidgets.QLabel(self.F4)
        self.TL4.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL4.setText("")
        self.TL4.setWordWrap(True)
        self.TL4.setObjectName("TL4")
        self.gridLayout.addWidget(self.F4, 1, 0, 1, 1)
        self.F5 = QtWidgets.QFrame(self.frame_4)
        self.F5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F5.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.F5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F5.setObjectName("F5")
        self.T5 = QtWidgets.QLabel(self.F5)
        self.T5.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T5.setStyleSheet("background-color: rgb(255, 255, 255,50%);")
        self.T5.setText("")
        self.T5.setScaledContents(True)
        self.T5.setObjectName("T5")
        self.TL5 = QtWidgets.QLabel(self.F5)
        self.TL5.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL5.setText("")
        self.TL5.setWordWrap(True)
        self.TL5.setObjectName("TL5")
        self.gridLayout.addWidget(self.F5, 1, 1, 1, 1)
        self.F6 = QtWidgets.QFrame(self.frame_4)
        self.F6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F6.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}\n"
"")
        self.F6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F6.setObjectName("F6")
        self.T6 = QtWidgets.QLabel(self.F6)
        self.T6.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T6.setStyleSheet("background-color: rgb(255, 255, 255,50%);")
        self.T6.setText("")
        self.T6.setScaledContents(True)
        self.T6.setObjectName("T6")
        self.TL6 = QtWidgets.QLabel(self.F6)
        self.TL6.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL6.setText("")
        self.TL6.setWordWrap(True)
        self.TL6.setObjectName("TL6")
        self.gridLayout.addWidget(self.F6, 1, 2, 1, 1)
        self.F7 = QtWidgets.QFrame(self.frame_4)
        self.F7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F7.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.F7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F7.setObjectName("F7")
        self.T7 = QtWidgets.QLabel(self.F7)
        self.T7.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T7.setStyleSheet("background-color: rgb(255, 255, 255,50%);")
        self.T7.setText("")
        self.T7.setScaledContents(True)
        self.T7.setObjectName("T7")
        self.TL7 = QtWidgets.QLabel(self.F7)
        self.TL7.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL7.setText("")
        self.TL7.setWordWrap(True)
        self.TL7.setObjectName("TL7")
        self.gridLayout.addWidget(self.F7, 2, 0, 1, 1)
        self.F8 = QtWidgets.QFrame(self.frame_4)
        self.F8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F8.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.F8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F8.setObjectName("F8")
        self.T8 = QtWidgets.QLabel(self.F8)
        self.T8.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T8.setStyleSheet("background-color: rgb(255, 255, 255,50%);")
        self.T8.setText("")
        self.T8.setScaledContents(True)
        self.T8.setObjectName("T8")
        self.TL8 = QtWidgets.QLabel(self.F8)
        self.TL8.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL8.setText("")
        self.TL8.setWordWrap(True)
        self.TL8.setObjectName("TL8")
        self.gridLayout.addWidget(self.F8, 2, 1, 1, 1)
        self.F9 = QtWidgets.QFrame(self.frame_4)
        self.F9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F9.setStyleSheet("QFrame\n"
"{\n"
"\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QFrame:hover\n"
"{\n"
"    background-color: rgb(17, 17, 17);\n"
"}")
        self.F9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F9.setObjectName("F9")
        self.T9 = QtWidgets.QLabel(self.F9)
        self.T9.setGeometry(QtCore.QRect(12, 10, 200, 140))
        self.T9.setStyleSheet("background-color: rgb(255, 255, 255,50%);")
        self.T9.setText("")
        self.T9.setScaledContents(True)
        self.T9.setObjectName("T9")
        self.TL9 = QtWidgets.QLabel(self.F9)
        self.TL9.setGeometry(QtCore.QRect(10, 160, 201, 30))
        self.TL9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Arial\";\n"
"background:transparent;")
        self.TL9.setText("")
        self.TL9.setWordWrap(True)
        self.TL9.setObjectName("TL9")
        self.gridLayout.addWidget(self.F9, 2, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.Next_page_btn = QtWidgets.QPushButton(self.frame_7)
        self.Next_page_btn.setGeometry(QtCore.QRect(620, 10, 91, 40))
        self.Next_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Next_page_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Next_page_btn.setStyleSheet("QPushButton\n"
"{\n"
"\n"
"    background:transparent;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ff004f;\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Icons/Next Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Next_page_btn.setIcon(icon10)
        self.Next_page_btn.setIconSize(QtCore.QSize(30, 30))
        self.Next_page_btn.setObjectName("Next_page_btn")
        self.previous_page_btn = QtWidgets.QPushButton(self.frame_7)
        self.previous_page_btn.setGeometry(QtCore.QRect(10, 10, 121, 40))
        self.previous_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previous_page_btn.setStyleSheet("QPushButton\n"
"{\n"
"\n"
"    background:transparent;\n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ff004f;\n"
"}")
        
        
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Icons/Previous Icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_page_btn.setIcon(icon11)
        self.previous_page_btn.setIconSize(QtCore.QSize(30, 30))
        self.previous_page_btn.setObjectName("previous_page_btn")
        self.verticalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.Main_Page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name_txt.setPlaceholderText(_translate("MainWindow", "Name"))
        self.Email_txt.setPlaceholderText(_translate("MainWindow", "Email Address"))
        self.otp_txt.setPlaceholderText(_translate("MainWindow", "One Time Password"))
        self.otp_button.setText(_translate("MainWindow", "Send OTP"))
        self.Submit_button.setText(_translate("MainWindow", "Submit"))
        self.Home_Menu.setText(_translate("MainWindow", "Home"))
        self.Search_Menu.setText(_translate("MainWindow", "Search"))
        self.Favourite_Menu.setText(_translate("MainWindow", "Favourite"))
        self.label_3.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", ""))
        self.Favourite_btn.setToolTip(_translate("MainWindow", "Add to Favourite"))
        self.mp3_btn.setToolTip(_translate("MainWindow", "Download Mp3 Format"))
        self.mp4_btn.setToolTip(_translate("MainWindow", "Download Mp4 Format"))
        self.Search_txt.setPlaceholderText(_translate("MainWindow", "Searching..."))
        self.Next_page_btn.setText(_translate("MainWindow", "Next  "))
        self.previous_page_btn.setText(_translate("MainWindow", "  Previous"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
